### ISSUE TITLE
Skip Link component inside Template

### ISSUE THREAD

**Issue by MartinDM** [surevine/govuk-react-jsx#115]
v5.1.0

We're using the `Template` component, and passing in an object to prop `skiplink` matching that defined in the `propTypes`...

I understand the Template _should_ in any case, render out a skiplink with the default text defined in the defaultProps if none supplied.

However, even when re-defining the value using the prop, no link content is shown. The link is rendered as expected, but there's no text inside it. The link appears to ignore any passed-in values and its own defaults.

Is this a known bug? I notice it occurring on this repo's govuk-react-jsx demo page too... Am I missing something in using this prop to define the link?

Thanks in advance for any pointers?

**Comment by andymantell** [comment]
oh well spotted. I've had a quick look and the skiplink component itself is actually working fine, but it's expecting a `children` prop and not a `text` prop. But the <Template> component passes `text` in it's default props.

So it's a bug in the template, not a bug in the skiplink as such.

Should be an easy fix though. I can pick this up this weekend and get a release out.

In the meantime if you need to unblock yourself, you should be able to pass `children` instead of `text` via the Template when you call it. The bug is only in the default props of the template...

**Comment by andymantell** [comment]
Hi Martin.

This is now released as govuk-react-jsx@6.0.0.

As per the release notes https://github.com/surevine/govuk-react-jsx/releases/tag/v6.0.0 - the major version bump was because of a necessary data structure change to tables. If you're not using tables then it should be a straight update.

Note also that govuk-frontend is bumped to 3.12.0

Hope this fixes things for you!
