### ISSUE TITLE
How to turn on validation errors for conditional fields

### ISSUE THREAD

**Issue by brightpixels** [surevine/govuk-react-jsx#46]
Hello,
I am struggling to work out how to turn on validation errors for conditional fields.

For example: https://surevine.github.io/govuk-react-jsx/?path=/story/checkboxes--with-optional-form-group-classes-showing-group-error

The phone number should only show if the checkbox is 'touched' and the input is blank (or fails validation). The error is part of the children array for the conditional and not sure how to make this array contain the error span only if the checkbox has been checked.

By the way, I am using `react-form-hooks` package for form state management but I have tried just simplifying it without this package just to see how I can make the error message conditional but no luck.

**Comment by andymantell** [comment]
Hi. Can you confirm that you are using `react-form-hooks` or `react-hook-form`. You state that you are using `react-form-hooks`, but the code examples in ticket #45 would suggest you are using `react-hook-form`

**Comment by andymantell** [comment]
Assuming you are using `react-hook-form`, I have put together a demo of simple field validation as well as conditional field validation.

I don't think conditional field validation is supported by `react-hook-form` on it's own, or at least I couldn't see how to make it work. It only seems to cater for simple field-level validation. I have therefore used `yup` (Since react-hook-form provides an option to use this) and made the following demo:

https://codesandbox.io/s/govuk-react-jsx-cra-react-hook-form-f8rrd

Couple of things to note:
- `react-hook-form` seems to forget the fields you've registered if you type anything in the codesandbox editor - you have to refresh the little codesandbox browser each time you make code changes
- As per #43 and #42 - my ErrorSummary component doesn't properly focus the fields in codesandbox. I plan to move away from using it but for now just bear that in mind.

Hope this helps.

**Comment by brightpixels** [comment]
Sorry about the typo, and you are right, I meant react-hook-form!!! Thanks very much, this is perfect.
